openapi: 3.1.0
info:
  title: Task API
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Local development servers
  - url: https://task-api-9yct.onrender.com
    description: Production server on render
tags:
  - name: Tasks
    description: Task-related endpoints
paths:
    $ref: paths/tasks.yaml
